### PR TITLE
ibgp-over-ebgp plugin

### PR DESCRIPTION
**Pull request by jbemmel**
A separate plugin to augment the bgp.neighbor lists with additional ebgp peers, based on an optional 'underlay_as' attribute per node

The module assumes bgp.as is the ibgp AS, and the regular bgp module is used to configure the ibgp peerings.

In the resulting bgp.neighbors list, a 'local_as' attribute is added for eBGP peers. The bgp templates will have to be updated to apply this (optional) attribute where needed.

Fixes https://github.com/ipspace/netsim-tools/issues/163

### CODE REVIEW

**Comment by ipspace** [comment]
In a word: **NO**.

You managed to reinvent Enterprise MIB. There's a reason you won't find "if device == Nokia then" in OpenConfig YANG data models.

Creating a separate copy of the BGP logic is bad (what if we change it to support things like #181), hard-coding plugin name into the BGP module is as appropriate as hard-coding the IP address of the database server into your web application, or hard-coding the device or vendor name in a standard YANG model.

I would suggest you start with another BGP node attribute (for example, **underlay_as**) which can be set in nodes or groups (don't try to overload the meaning of bgp.as or bgp.as_list). If you'd like to have **ibgp_over_ebgp** attribute with two autonomous systems, then process that in the **init** code to set global or node **bgp.as** and **bgp.underlay_as** (or similar).

In the **post_transform** code iterate over all links, identify situations where neighbor **underlay_as** are different and add EBGP sessions with **local_as** to node **bgp.neighbor** list, effectively _augmenting_ what BGP module does not _replacing_ it.

As for the actual configuration, you could either modify exiting BGP templates, or have configuration templates in the plugin directory and add them to the node **config** attribute (see https://github.com/ipspace/netsim-examples/tree/master/routing/anycast-mpls/bgp-anycast). _Local AS_ might be a useful addition to the BGP module, so in this particular case it's probably best to have it in the BGP template.

**Comment by jbemmel** [comment]
I added the 'print' in the bgp module just to highlight the point where the as_list model breaks down, as it only keeps the last seen as per node. The reference to the plug-in name can be removed, I was just thinking you may want to put some sort of warning there (or even an error - as the config is ambiguous)

I ended up where I did because I started modeling bgp.as_list in a wrong way (with duplicate members) and then tried to retrofit that model. I can see you prefer to not change bgp.as_list, I'll see what I can do

**Comment by ipspace** [comment]
Yet again, you picked up a few of my commits. Please rebase and resubmit the PR. Thank you!

**Comment by jbemmel** [comment]
Superseded by https://github.com/ipspace/netsim-tools/pull/184

**Pull request closed without merging**
