### PR TITLE
Fix NXOS under AMD CPUs

### PR DESCRIPTION
**Pull request by Kircheneer**
#9

### CODE REVIEW

**Comment by Kircheneer** [comment]
So, while reviewing this I realized that my platform detection code only worked properly under Windows. I've implemented this for my Ubuntu 20.04 VM and I think it should run well under most modern AMD systems. I've put in a check for MacOS as well but I don't have a device for testing. We could also assume Intel in case of MacOS - I'm not well versed in what kind of hardware Apple devices have built-in.

**Comment by Kircheneer** [comment]
Don't look into this too closely yet - I will need some more time until its ready.

**Comment by ipspace** [comment]
```
uname -v
Darwin Kernel Version 19.6.0: Mon Apr 12 20:57:45 PDT 2021; root:xnu-6153.141.28.1~1/RELEASE_X86_64
```

```
$ python3
Python 3.9.1 (default, Jan  8 2021, 17:17:17)
[Clang 12.0.0 (clang-1200.0.32.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.processor()
'i386'
>>>
```

OSX is OK - Apple uses Intel CPUs, and whatever is reported is NOT anywhere close to AMD.

**Comment by Kircheneer** [comment]
I've done the following things:
- Change the Vagrantfile template for NXOS so that it
  - Runs the Cisco supplied Vagrant box properly
  - Runs properly under my AMD system
- Add a short hint in the docs to the Cisco supplied Vagrant box and how to use it
- Work in your comment about the logic swapping

The only unknown is: Does your blog-post built Vagrant box still work under these settings?

**Comment by ipspace** [comment]
Of course it broke my setup. What else could one expect ;) 

Got it to work with your **mutate** trick (which I love) and a tiny change in the template (and I suspect even my original box would work with that change).

**Comment by Kircheneer** [comment]
Go thank Dinesh Dutt for that, he showed me that trick! Just keep in mind the default credentials for the Cisco supplied box are admin:admin - hence my adding the username to the initial configuration for NXOS.

**Pull request merged**
