### PR TITLE
Platforms: Cumulus eBGP unnumbered support

### PR DESCRIPTION
**Pull request by petercrocker**
Platforms: Add initial support for ebgp unnumbered on Cumulus

* mod `netsim/ansible/templates/bgp/cumulus.j2` to change logic:
  * if bgp neighbor is unnumbered, don't bother with BGP AFs since unnumbered can't distinguish them
  * else add per-AF peer info 
  
* mod `netsim/modules/bgp.py to support ebgp unnumbered:
  * Sorry about the python formatting changes! See issue filed so I don't ever do this again, or I can resubmit
  * Lines 58-62: Set unnumbered interface ip to `True` and capture local interface name
  * Line 235: pass local interface to function via `extra_data`

### CODE REVIEW

**Comment by petercrocker** [comment]
I'd suggest holding off on this until after the bug-fix release, and it gets the appropriate test coverage.

**Comment by petercrocker** [comment]
I can see some obvious changes I need to make for tests:

```
netsim/modules/bgp.py:58: error: Item "Dict[Any, Any]" of "Optional[Dict[Any, Any]]" has no attribute "unnumbered"
netsim/modules/bgp.py:58: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "unnumbered"
netsim/modules/bgp.py:60: error: Item "Dict[Any, Any]" of "Optional[Dict[Any, Any]]" has no attribute "local_if"
netsim/modules/bgp.py:60: error: Item "None" of "Optional[Dict[Any, Any]]" has no attribute "local_if"
```

I'll make these tomorrow.

**Comment by petercrocker** [comment]
Ok @ipspace this is now ready for review

**Comment by ipspace** [comment]
Restored the formatting of **bgp.py** and amended the squashed commit. 

Thanks a million for implementing this one... but try not to do module-level reformats too often ;)

**Comment by petercrocker** [comment]
Sorry about that, this was my learning curve for a number of things: formatting, the test framework, and how the python code is structured, so hopefully next time will be much easier on all of us!

**Pull request merged**
